#ifndef _PAGES_H
#define _PAGES_H
#include <string.h>

String body_page_wifi_scan = "<!DOCTYPE html>"
"<html>"
"<head>"
"<title>Temp Config</title>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<meta charset='UTF-8'>"
"<style>"
  "tr:nth-child(even){"
  "          background-color: #ddd;"
  "      }"
  ".btn{"
    "background-color: rgb(179, 179, 179);"
    "color: white;"
    "padding: 14px 20px;"
    "margin: 8px 0;"
    "border: none;"
    "cursor: pointer;"
  "}"
  ".center{"
  "position: absolute;"
  "top: 50%;"
  "left: 50%;"
  "transform: translate(-50%, -50%);"
  "width: 300px;"
  "background: white;"
  "border-radius: 10px;"
  "box-shadow: 10px 10px 15px rgba(0,0,0,0.05);"
  "}"
  "input{"
  "margin: 8px 0;"
  "border-radius: 4px;"
  "}"
  ".center h1{"
  "text-align: center;"
  "padding: 20px 0;"
  "border-bottom: 1px solid silver;"
  "}"
"</style>"
"</head>"
"<body style='background-color:#eee;'>"
"<div class='center'>"
"<center><p>Ingrese Wifi</p></center>"
"<form action='guardar_conf' method='get'>"
"<center>SSID <input placeholder='Nombre Wifi' name='ssid' type='text'></center>"
"<br>"
"<center>PASS <input placeholder='Password' name='pass' type='password'></center><br>"
"<center><input class='btn' type='submit' value='GUARDAR'/></center><br>"
"</form>"
"<center><a href='escanear'><button class='btn'>ESCANEAR</button></a><br><br>";

String footer_html = "    </div>"
"    <footer>"
"        <p>Dev: Cristian Carreras</p>"
"    </footer>   "
"</body>"
""
"</html>";

String header_html = "<!DOCTYPE html>"
"<html lang='es'>"
"<head>"
"<meta charset=' UTF-8 '>"
"    <meta http-equiv='X-UA-Compatible' content='IE=edge'>"
"    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"    <title>Temperatura & Humedad</title>"
"    <style>"
"        * {"
"            margin: 0;"
"            padding: 0;"
"            color: rgb(93, 190, 214);"
"            margin-top: 10px;"
"        }"
"        body {"
"            font-family: Arial, Helvetica, sans-serif;"
"            font-size: 14px;"
"            background-color: #333333;"
"        }"
"        h1 {"
"            "
"            text-align: center;"
"        }"
"        .container {"
"            width: 50%;"
"            height: 100%;"
"            display: flex;"
"            flex-direction: column;"
"            justify-content: center;"
"            align-items: center;"
"            margin: auto;"
"            border-radius: 10px;"
"        }"
"        .title {"
"            border: 1px solid;"
"            border-image-slice: 1;"
"            border-image-source: linear-gradient(to left, #54d0d4, #9ad53a);"
"            border-radius: 5px;"
"            font-size: large;"
"            text-align: center;"
"            width: 80%;"
"            margin: 5%;"
""
"        }"
"        .content-table {"
"            font-size:x-large;"
"            margin-bottom: 5%;"
"        }"
"        .border-gradient {"
"        border: 5px solid;"
"        border-image-slice: 1;"
"        border-image-source: linear-gradient(to left, #54d0d4, #9ad53a);"
"        }"
"        footer{"
"            position: absolute;"
"            bottom: 0;"
"            width: 100%;"
"            height: 5%;"
"            text-align: center;"
"            font-size: small;"
"        }"
"        p{"
"            color:rgb(93, 190, 214);"
"        }"
""
"    </style>"
"</head>";

String body_page_tempHum = "<body>"
"    <div class='container border-gradient'>"
"        <div class='title'>"
"            <h1>Temperatura</h1>"
"            <h1>&</h1>"
"            <h1>Humedad</h1>"
"        </div>"
"        <div class='content-table'>"
"            <br>"
"            <table>"
"                <tr>"
"                    <th>Temperatura |</th>"
"                    <th>Humedad</th>"
"                </tr>"
"                <tr>"
"                    <td>{{temp}}</td>"
"                    <td>{{humidity}}</td>"
"                </tr>"
"            </table>"
"    </div>";

#endif